### ISSUE TITLE
finish and debug MQTT controller

### ISSUE THREAD

**Issue by sleiner** [Yottabits/102shows#2]

**Comment by domiko96** [comment]
wo ist denn da was mit MQTT? Ich sehe nur led controls.

**Comment by sleiner** [comment]
Du musst im richtigen Branch schauen: `super-unstable-ugly-shit`
Da liegt `MQTTController.py`:  https://github.com/Yottabits/DotStar/blob/super-unstable-ugly-shit/MQTTControl.py

**Comment by sleiner** [comment]
implemented - works in theory - test on a real strip must still be made

**Comment by sleiner** [comment]
works 👍
